name: Build and Push Docker Image

on:
  push:
    branches:
      - Tp2

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Dockerfile with hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./Dockerfile"

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: docker/login-action@v3
        with:
          registry: efreidevops.azurecr.io
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20230580:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20230580:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-20230580
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20230580:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: 20230580
          secure-environment-variables: API_KEY=$({secrets.OPENWEATHER_API_KEY})
          location: 'francecentral'
